2023-08-24 02:55:01 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Constraint "PRIMARY KEY | UNIQUE (ID_SEGURADO)" not found; SQL statement:
ALTER TABLE tb_psg_veiculo
  ADD CONSTRAINT tb_psg_veiculo_id_segurado_fk FOREIGN KEY ( tb_psg_segurado_id_segurado )
    REFERENCES tb_psg_segurado ( id_segurado ) [90057-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:644)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.command.ddl.AlterTableAddConstraint.tryUpdate(AlterTableAddConstraint.java:259)
	at org.h2.command.ddl.AlterTableAddConstraint.update(AlterTableAddConstraint.java:74)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:46)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:188)
	at org.h2.server.web.WebThread.run(WebThread.java:101)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-08-26 13:33:18 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TB_PSG_ORDEM_SERVICO" already exists; SQL statement:
CREATE TABLE tb_psg_ordem_servico (
  id_ordem_servico                        NUMBER NOT NULL,
  tipo_sinistro                           VARCHAR2(3000) NOT NULL,
  data_sinistro                           DATE NOT NULL,
  tb_psg_segurado_id_segurado             NUMBER NOT NULL,
  descricao_sinistro                      VARCHAR2(3000) NOT NULL,
  tb_psg_apol_s_id_apol_s                 NUMBER NOT NULL, 
  tb_psg_local_sini_id_local_sini         NUMBER NOT NULL
) [42101-220]
2023-08-26 13:33:50 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE tb_psg_ordem_servico (\000d\000a  id_ordem_servico                        NUMBER NOT NULL,\000d\000a  tipo_sinistro                           VARCHAR2(3000) NOT NULL,\000d\000a  data_sinistro                           DATE NOT NULL,\000d\000a  docto_segurado             NUMBER NOT NULL,\000d\000a  descricao_sinistro                      VARCHAR2(3000) NOT NULL,[*])"; expected "identifier"; SQL statement:
CREATE TABLE tb_psg_ordem_servico (
  id_ordem_servico                        NUMBER NOT NULL,
  tipo_sinistro                           VARCHAR2(3000) NOT NULL,
  data_sinistro                           DATE NOT NULL,
  docto_segurado             NUMBER NOT NULL,
  descricao_sinistro                      VARCHAR2(3000) NOT NULL,) [42001-220]
2023-08-26 13:33:50 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TB_PSG_ORDEM_SERVICO" not found; SQL statement:
drop table tb_psg_ordem_servico [42102-220]
2023-08-26 13:34:00 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE tb_psg_ordem_servico (\000d\000a  id_ordem_servico                        NUMBER NOT NULL,\000d\000a  tipo_sinistro                           VARCHAR2(3000) NOT NULL,\000d\000a  data_sinistro                           DATE NOT NULL,\000d\000a  docto_segurado             NUMBER NOT NULL,\000d\000a  descricao_sinistro                      VARCHAR2(3000) NOT NULL,[*])"; expected "identifier"; SQL statement:
CREATE TABLE tb_psg_ordem_servico (
  id_ordem_servico                        NUMBER NOT NULL,
  tipo_sinistro                           VARCHAR2(3000) NOT NULL,
  data_sinistro                           DATE NOT NULL,
  docto_segurado             NUMBER NOT NULL,
  descricao_sinistro                      VARCHAR2(3000) NOT NULL,) [42001-220]
2023-08-26 13:34:13 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE tb_psg_ordem_servico (\000d\000a  id_ordem_servico                        NUMBER NOT NULL,\000d\000a  tipo_sinistro                           VARCHAR2(3000) NOT NULL,\000d\000a  data_sinistro                           DATE NOT NULL,\000d\000a  docto_segurado             NUMBER NOT NULL,\000d\000a  descricao_sinistro                      VARCHAR2(3000) NOT NULL,[*])"; expected "identifier"; SQL statement:
CREATE TABLE tb_psg_ordem_servico (
  id_ordem_servico                        NUMBER NOT NULL,
  tipo_sinistro                           VARCHAR2(3000) NOT NULL,
  data_sinistro                           DATE NOT NULL,
  docto_segurado             NUMBER NOT NULL,
  descricao_sinistro                      VARCHAR2(3000) NOT NULL,) [42001-220]
2023-08-26 13:34:13 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TB_PSG_ORDEM_SERVICO" not found; SQL statement:
drop table tb_psg_ordem_servico [42102-220]
2023-08-26 14:14:27 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*]desc TB_PSG_ORDEM_SERVICO"; expected "DELETE, DROP, DECLARE, DEALLOCATE"; SQL statement:
desc TB_PSG_ORDEM_SERVICO [42001-220]
2023-08-26 14:14:39 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*]desc TB_PSG_ORDEM_SERVICO"; expected "DELETE, DROP, DECLARE, DEALLOCATE"; SQL statement:
desc TB_PSG_ORDEM_SERVICO [42001-220]
2023-08-26 14:20:36 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*]desc TB_PSG_ORDEM_SERVICO"; expected "DELETE, DROP, DECLARE, DEALLOCATE"; SQL statement:
desc TB_PSG_ORDEM_SERVICO [42001-220]
2023-08-26 14:20:36 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "drop table TB_PSG_ORDEM_SERVICO \000d\000a[*]CREATE TABLE tb_psg_ordem_servico (\000d\000a  id_ordem_servico                        NUMBER NOT NULL,\000d\000a  tipo_sinistro                           NUMBER NOT NULL,\000d\000a  data_sinistro                           DATE NOT NULL,\000d\000a  tb_psg_segurado_id_segurado             NUMBER NOT NULL,\000d\000a  descricao_sinistro                      VARCHAR2(3000) NOT NULL,\000d\000a  tb_psg_apol_s_id_apol_s                 NUMBER NOT NULL, \000d\000a  tb_psg_local_sini_id_local_sini         NUMBER NOT NULL\000d\000a)"; SQL statement:
drop table TB_PSG_ORDEM_SERVICO 
CREATE TABLE tb_psg_ordem_servico (
  id_ordem_servico                        NUMBER NOT NULL,
  tipo_sinistro                           NUMBER NOT NULL,
  data_sinistro                           DATE NOT NULL,
  tb_psg_segurado_id_segurado             NUMBER NOT NULL,
  descricao_sinistro                      VARCHAR2(3000) NOT NULL,
  tb_psg_apol_s_id_apol_s                 NUMBER NOT NULL, 
  tb_psg_local_sini_id_local_sini         NUMBER NOT NULL
) [42000-220]
2023-08-26 14:20:39 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*]desc TB_PSG_ORDEM_SERVICO"; expected "DELETE, DROP, DECLARE, DEALLOCATE"; SQL statement:
desc TB_PSG_ORDEM_SERVICO [42001-220]
2023-08-26 14:20:39 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "drop table TB_PSG_ORDEM_SERVICO \000d\000a[*]CREATE TABLE tb_psg_ordem_servico (\000d\000a  id_ordem_servico                        NUMBER NOT NULL,\000d\000a  tipo_sinistro                           NUMBER NOT NULL,\000d\000a  data_sinistro                           DATE NOT NULL,\000d\000a  tb_psg_segurado_id_segurado             NUMBER NOT NULL,\000d\000a  descricao_sinistro                      VARCHAR2(3000) NOT NULL,\000d\000a  tb_psg_apol_s_id_apol_s                 NUMBER NOT NULL, \000d\000a  tb_psg_local_sini_id_local_sini         NUMBER NOT NULL\000d\000a)"; SQL statement:
drop table TB_PSG_ORDEM_SERVICO 
CREATE TABLE tb_psg_ordem_servico (
  id_ordem_servico                        NUMBER NOT NULL,
  tipo_sinistro                           NUMBER NOT NULL,
  data_sinistro                           DATE NOT NULL,
  tb_psg_segurado_id_segurado             NUMBER NOT NULL,
  descricao_sinistro                      VARCHAR2(3000) NOT NULL,
  tb_psg_apol_s_id_apol_s                 NUMBER NOT NULL, 
  tb_psg_local_sini_id_local_sini         NUMBER NOT NULL
) [42000-220]
2023-08-26 14:21:09 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE tb_psg_ordem_servico (\000d\000a  id_ordem_servico                        NUMBER NOT NULL,\000d\000a  tipo_sinistro                           NUMBER NOT NULL,\000d\000a  data_sinistro                           DATE,\000d\000a  docto_segurado             NUMBER NOT NULL,\000d\000a  descricao_sinistro                      VARCHAR2(3000) NOT NULL,\000d\000a[*])"; expected "identifier"; SQL statement:
CREATE TABLE tb_psg_ordem_servico (
  id_ordem_servico                        NUMBER NOT NULL,
  tipo_sinistro                           NUMBER NOT NULL,
  data_sinistro                           DATE,
  docto_segurado             NUMBER NOT NULL,
  descricao_sinistro                      VARCHAR2(3000) NOT NULL,
) [42001-220]
2023-08-26 14:41:17 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*]a"; expected "ALTER, ANALYZE"; SQL statement:
a [42001-220]
2023-08-26 15:01:49 jdbc[5]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TB_PSG_ORDEM_SERVICO" already exists; SQL statement:
CREATE TABLE tb_psg_ordem_servico (
  id_ordem_servico                        NUMBER NOT NULL,
  tipo_sinistro                           NUMBER NOT NULL,
  data_sinistro                           DATE,
 hora_sinistro timestamp,
  docto_segurado             NUMBER NOT NULL,
  descricao_sinistro                      VARCHAR2(3000) NOT NULL
) [42101-220]
2023-08-26 15:29:50 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Column "TIPO_SINSITRO" not found; SQL statement:
Insert into TB_PSG_ORDEM_SERVICO (TIPO_SINSITRO,DESCRICAO_SINISTRO, DOCTO_SEGURADO) VALUES (?,?,?) [42122-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.getColumn(Table.java:759)
	at org.h2.command.Parser.parseColumn(Parser.java:1300)
	at org.h2.command.Parser.parseColumnList(Parser.java:1285)
	at org.h2.command.Parser.parseInsert(Parser.java:1672)
	at org.h2.command.Parser.parsePrepared(Parser.java:822)
	at org.h2.command.Parser.parse(Parser.java:697)
	at org.h2.command.Parser.parse(Parser.java:669)
	at org.h2.command.Parser.prepareCommand(Parser.java:577)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:634)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:557)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1116)
	at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:92)
	at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:288)
	at beans.ChamadoDAO.insereChamado(ChamadoDAO.java:19)
	at main.GerenciamentoSinistros.main(GerenciamentoSinistros.java:62)
2023-08-27 18:39:24 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "alter table tb_psg_ordem_servico [*]modify docto_segurado (varchar2(300))"; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
alter table tb_psg_ordem_servico modify docto_segurado (varchar2(300)) [42001-220]
2023-08-27 18:40:10 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "alter table tb_psg_ordem_servico [*]modify column docto_segurado (varchar2(300))"; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
alter table tb_psg_ordem_servico modify column docto_segurado (varchar2(300)) [42001-220]
2023-09-02 13:59:19 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Duplicate column name "STATUS_OS"; SQL statement:
alter table tb_psg_ordem_servico add status_os char(1) [42121-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:514)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.table.Table.setColumns(Table.java:494)
	at org.h2.table.TableBase.<init>(TableBase.java:73)
	at org.h2.mvstore.db.MVTable.<init>(MVTable.java:139)
	at org.h2.mvstore.db.Store.createTable(Store.java:216)
	at org.h2.schema.Schema.createTable(Schema.java:797)
	at org.h2.command.ddl.AlterTableAlterColumn.cloneTableStructure(AlterTableAlterColumn.java:454)
	at org.h2.command.ddl.AlterTableAlterColumn.copyData(AlterTableAlterColumn.java:339)
	at org.h2.command.ddl.AlterTableAlterColumn.update(AlterTableAlterColumn.java:242)
	at org.h2.command.CommandContainer.update(CommandContainer.java:169)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.h2.server.web.WebApp.getResult(WebApp.java:1345)
	at org.h2.server.web.WebApp.query(WebApp.java:1143)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1109)
	at org.h2.server.web.WebApp$1.next(WebApp.java:1096)
	at org.h2.server.web.WebThread.process(WebThread.java:188)
	at org.h2.server.web.WebThread.run(WebThread.java:101)
	at java.base/java.lang.Thread.run(Thread.java:831)
2023-09-02 13:59:38 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "[*]tb_psg_ordem_servico where id_ordem_servico = 33"; expected "TRUNCATE"; SQL statement:
tb_psg_ordem_servico where id_ordem_servico = 33 [42001-220]
2023-09-02 14:04:18 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select count(1) from tb_psg_ordem_servico  where docto_segurado  = 45633416813 and status_os  != 'E'[*]"""; SQL statement:
select count(1) from tb_psg_ordem_servico  where docto_segurado  = 45633416813 and status_os  != 'E'" [42000-220]
2023-09-02 14:05:42 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select *from tb_psg_ordem_servico  \000d\000ainsert [*]into tb_psg_ordem_servico  (tipo_sinistro,docto_segurado,descricao_sinistro,status_os) values (3,45633416813,'alegria','A')"; SQL statement:
select *from tb_psg_ordem_servico  
insert into tb_psg_ordem_servico  (tipo_sinistro,docto_segurado,descricao_sinistro,status_os) values (3,45633416813,'alegria','A') [42000-220]
2023-09-02 14:05:57 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "select *from tb_psg_ordem_servico  \000d\000ainsert [*]into tb_psg_ordem_servico  (tipo_sinistro,docto_segurado,descricao_sinistro,status_os) values (3,45633416813,'alegria','A')"; SQL statement:
select *from tb_psg_ordem_servico  
insert into tb_psg_ordem_servico  (tipo_sinistro,docto_segurado,descricao_sinistro,status_os) values (3,45633416813,'alegria','A') [42000-220]
2023-09-11 02:49:01 jdbc[4]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "Insert into tb_psg_veiculo(placa_veiculo,[*],estado_veiculo,especificacoes_veiculo, values ( )"; expected "identifier"; SQL statement:
Insert into tb_psg_veiculo(placa_veiculo,,estado_veiculo,especificacoes_veiculo, values ( ) [42001-220]
2023-09-11 02:49:01 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at beans.ConnectionFactory.criaConexao(ConnectionFactory.java:17)
	at beans.ChamadoDAO.<init>(ChamadoDAO.java:11)
	at beans.DAOTest.setUp(DAOTest.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 53 more
2023-09-11 02:49:01 jdbc[5]: null
org.h2.message.DbException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:190)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:132)
	at org.h2.Driver.connect(Driver.java:59)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:681)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:229)
	at beans.ConnectionFactory.criaConexao(ConnectionFactory.java:17)
	at beans.ChamadoDAO.<init>(ChamadoDAO.java:11)
	at beans.DAOTest.setUp(DAOTest.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42)
	at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80)
	at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: The connection was not closed by the application and is garbage collected [90018-220]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:690)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:489)
	... 53 more
2023-09-11 22:04:34 jdbc[3]: exception
org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TB_PSG_VEICULO" already exists; SQL statement:
CREATE TABLE TB_PSG_VEICULO (
    PLACA_VEICULO VARCHAR(255),
    ESTADO_VEICULO CHAR(1),
    ESPECIFICACOES_VEICULO VARCHAR(255),
    ID_VEICULO INT,
    TB_PSG_SEGURADO_ID_SEGURADO INT,
    NUM_CHASSI_VEICULO BIGINT,
    DOCTO_SEGURADO BIGINT
) [42101-220]
